# Generated by Django 4.1 on 2022-09-09 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grade", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fullname", models.CharField(max_length=250)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_guest", models.BooleanField(blank=True, default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("STUDENT", "Student"),
                            ("TEACHER", "Teacher"),
                            ("STAFF", "Staff"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="TeacherAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250)),
                ("contact", models.BigIntegerField()),
                ("qualification", models.CharField(max_length=250)),
                ("is_class_teacher", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ImageField(blank=True, null=True, upload_to="upload/staff"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250)),
                ("contact", models.BigIntegerField(blank=True, null=True)),
                (
                    "profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="upload/profile"
                    ),
                ),
                ("enroll_date", models.DateField(blank=True, null=True)),
                (
                    "fathers_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mothers_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("guardian_contact", models.BigIntegerField(blank=True, null=True)),
                (
                    "reffered_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("reffered_contact", models.BigIntegerField(blank=True, null=True)),
                (
                    "documents",
                    models.ImageField(
                        blank=True, null=True, upload_to="upload/documents"
                    ),
                ),
                ("entrance_grade", models.FloatField(blank=True, null=True)),
                (
                    "grade_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grade.grademodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250)),
                ("contact", models.BigIntegerField()),
                (
                    "profile",
                    models.ImageField(blank=True, null=True, upload_to="upload/staff"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("users.useraccount",),
            managers=[("teacher", django.db.models.manager.Manager()),],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("users.useraccount",),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("users.useraccount",),
            managers=[("teacher", django.db.models.manager.Manager()),],
        ),
    ]
