# Generated by Django 4.1 on 2022-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacheraccount",
            name="is_class_teacher",
            field=models.BooleanField(default=True),
        ),
    ]
