# Generated by Django 4.1 on 2022-09-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0001_initial"),
        ("users", "0002_alter_teacheraccount_is_class_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacheraccount",
            name="grade_id",
            field=models.ManyToManyField(to="grade.grademodel"),
        ),
    ]
