# Generated by Django 4.1 on 2022-09-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_teacheraccount_grade_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacheraccount",
            name="is_class_teacher",
            field=models.BooleanField(default=None),
        ),
    ]
