# Generated by Django 4.1 on 2022-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_teacheraccount_is_class_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacheraccount",
            name="is_class_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
