# Generated by Django 4.1 on 2022-09-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_studentaccount_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentaccount",
            name="documents",
            field=models.ImageField(
                blank=True, null=True, upload_to="upload/documents"
            ),
        ),
        migrations.AlterField(
            model_name="studentaccount",
            name="entrance_grade",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
