# Generated by Django 4.1 on 2022-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0002_remove_grademodel_section_section"),
        ("users", "0007_alter_studentaccount_documents_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentaccount", name="grade_id",),
        migrations.RemoveField(model_name="teacheraccount", name="grade_id",),
        migrations.AddField(
            model_name="studentaccount",
            name="section_id",
            field=models.ManyToManyField(to="grade.section"),
        ),
        migrations.AddField(
            model_name="teacheraccount",
            name="section_id",
            field=models.ManyToManyField(to="grade.section"),
        ),
    ]
