# Generated by Django 4.1 on 2022-09-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0003_alter_grademodel_grade"),
        ("users", "0008_remove_studentaccount_grade_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="studentaccount", name="section_id",),
        migrations.AddField(
            model_name="studentaccount",
            name="section_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grade.section",
            ),
        ),
    ]
