# Generated by Django 4.1 on 2022-09-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_teacheraccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='section_id',
        ),
    ]
