# Generated by Django 4.1 on 2022-09-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_alter_grademodel_grade'),
        ('users', '0012_remove_studentaccount_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.section'),
        ),
    ]
