# Generated by Django 4.1.2 on 2022-10-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studentaccount_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='useracc',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('STAFF', 'STAFF'), ('GUEST', 'GUEST')], default=None, max_length=50),
        ),
    ]
