# Generated by Django 4.1.2 on 2022-10-13 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_staffaccount_useracc_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
