# Generated by Django 4.1.2 on 2022-10-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_staffaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheraccount',
            name='useracc',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=50),
        ),
    ]
