# Generated by Django 4.1.2 on 2022-11-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_staffaccount_fullname_studentaccount_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
