# Generated by Django 4.1.2 on 2022-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_studentaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='useracc',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True),
        ),
    ]
