# Generated by Django 4.1 on 2022-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodel",
            name="credit_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
