# Generated by Django 4.1 on 2022-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grade", "0002_remove_grademodel_section_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grademodel",
            name="grade",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
