# Generated by Django 4.1 on 2022-09-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0008_remove_studentaccount_grade_id_and_more"),
        ("grade", "0002_remove_grademodel_section_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassTeacherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="grade.section"
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teacheraccount",
                    ),
                ),
            ],
        ),
    ]
